title: Tooth Fairy Flying Forecast
author: Fairy Mother
description: > # this means to ignore newlines until "baseurl:"
  Will the tooth fairy be flying?
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
